version: 0.0
os: linux
files:
  - source: target/
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
   - location: scripts/stop.sh
     runas: root
  AfterInstall:
   - location: scripts/start.sh
     runas: root
